AllCops:
  Exclude:
    - '**/metadata.rb'
    - '**/*.gemspec'
    - '**/version.rb'
    - 'Guardfile'

Metrics/AbcSize:
  Enabled: false

Metrics/LineLength:
  Max: 160

# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Enabled: false
