AllCops:
  Exclude:
    - '**/metadata.rb'
    - '**/*.gemspec'
    - '**/version.rb'
    - 'Guardfile'

ClassAndModuleChildren:
  Enabled: false
Documentation:
  Enabled: false

CollectionMethods:
  Enabled: false
LineLength:
  Max: 160
Metrics/MethodLength:
  Max: 30
